<?php

return [
    [
        'id' => 'ambition-adventure',
        'icon' => '🎯',
        'title' => 'Meet the Future [Name]',
        'description' => 'Setting goals and pursuing dreams',
        'skills' => ['Goal Setting', 'Future Planning', 'Self Discovery'],
        'activity' => 'Read a personalized story and answer quiz questions',
        'creates' => 'A 10-page storybook about your ambitions',
        'badge' => 'Dream Chaser',
        'personalization_questions' => [
            [
                'key' => 'dream_job',
                'type' => 'text',
                'question' => 'What do you dream of becoming when you grow up?',
                'placeholder' => 'Doctor, Engineer, Artist...',
            ],
            [
                'key' => 'why_dream',
                'type' => 'text',
                'question' => 'Why does this dream excite you?',
                'placeholder' => 'Share your reason...',
            ],
            [
                'key' => 'first_step',
                'type' => 'mcq',
                'question' => 'What would be your first step toward this dream?',
                'options' => [
                    'Learn more about it',
                    'Practice the skills needed',
                    'Talk to someone who does it',
                    'Start a small project',
                ],
            ],
            [
                'key' => 'superpower',
                'type' => 'chips',
                'question' => 'If you had a superpower to help achieve your dream, what would it be?',
                'options' => ['Super Learning', 'Time Travel', 'Mind Reading', 'Super Speed', 'Creativity Boost'],
            ],
        ],
    ],
    [
        'id' => 'innovation-station',
        'icon' => '💡',
        'title' => 'Innovation Station',
        'description' => 'Inventing solutions and thinking creatively',
        'skills' => ['Problem Solving', 'Creativity', 'Innovation'],
        'activity' => 'Brainstorm solutions and create inventions',
        'creates' => 'A 10-page innovation journal',
        'badge' => 'Inventor',
        'personalization_questions' => [
            [
                'key' => 'problem_to_solve',
                'type' => 'text',
                'question' => 'What problem in the world would you like to solve?',
                'placeholder' => 'Environmental, social, technological...',
            ],
            [
                'key' => 'invention_idea',
                'type' => 'text',
                'question' => 'What would you invent to solve this problem?',
                'placeholder' => 'Describe your invention...',
            ],
            [
                'key' => 'innovation_approach',
                'type' => 'mcq',
                'question' => 'How would you approach creating this invention?',
                'options' => [
                    'Start with research',
                    'Build a prototype',
                    'Team up with others',
                    'Learn from existing solutions',
                ],
            ],
            [
                'key' => 'inventor_trait',
                'type' => 'chips',
                'question' => 'What inventor trait do you have?',
                'options' => ['Curiosity', 'Persistence', 'Creativity', 'Logic', 'Courage'],
            ],
        ],
    ],
    [
        'id' => 'exploration-quest',
        'icon' => '🗺️',
        'title' => 'Exploration Quest',
        'description' => 'Discovering new places and cultures',
        'skills' => ['Geography', 'Cultural Awareness', 'Adventure'],
        'activity' => 'Explore different cultures and locations',
        'creates' => 'A 10-page travel journal',
        'badge' => 'World Explorer',
        'personalization_questions' => [
            [
                'key' => 'dream_destination',
                'type' => 'text',
                'question' => 'Where in the world would you most like to explore?',
                'placeholder' => 'Country, city, or region...',
            ],
            [
                'key' => 'exploration_reason',
                'type' => 'text',
                'question' => 'What draws you to this place?',
                'placeholder' => 'Culture, nature, history...',
            ],
            [
                'key' => 'explorer_style',
                'type' => 'mcq',
                'question' => 'What kind of explorer are you?',
                'options' => [
                    'Cultural adventurer',
                    'Nature lover',
                    'History detective',
                    'Food explorer',
                ],
            ],
            [
                'key' => 'exploration_companion',
                'type' => 'chips',
                'question' => 'Who would you bring on your exploration?',
                'options' => ['Family', 'Friends', 'A Guide', 'Solo Adventure', 'Pet Companion'],
            ],
        ],
    ],
    [
        'id' => 'green-planet-heroes',
        'icon' => '🌱',
        'title' => 'Green Planet Heroes',
        'description' => 'Environmental protection and sustainability',
        'skills' => ['Environmental Care', 'Sustainability', 'Climate Action'],
        'activity' => 'Learn about nature and climate action',
        'creates' => 'A 10-page eco-adventure story',
        'badge' => 'Planet Protector',
        'personalization_questions' => [
            [
                'key' => 'environmental_concern',
                'type' => 'text',
                'question' => 'What environmental issue concerns you most?',
                'placeholder' => 'Pollution, deforestation, climate change...',
            ],
            [
                'key' => 'eco_action',
                'type' => 'text',
                'question' => 'What action can you take to help the planet?',
                'placeholder' => 'Recycling, planting trees, reducing waste...',
            ],
            [
                'key' => 'green_hero_role',
                'type' => 'mcq',
                'question' => 'As a Green Planet Hero, what role suits you best?',
                'options' => [
                    'Educator - teaching others',
                    'Activist - leading change',
                    'Innovator - creating solutions',
                    'Protector - preserving nature',
                ],
            ],
            [
                'key' => 'eco_superpower',
                'type' => 'chips',
                'question' => 'What eco-superpower would you want?',
                'options' => ['Clean Air Creator', 'Tree Grower', 'Ocean Cleaner', 'Animal Communicator', 'Weather Controller'],
            ],
        ],
    ],
    [
        'id' => 'space-odyssey',
        'icon' => '🚀',
        'title' => 'Space Odyssey',
        'description' => 'Space exploration and astronomy',
        'skills' => ['Astronomy', 'Space Science', 'Exploration'],
        'activity' => 'Journey through the cosmos',
        'creates' => 'A 10-page space exploration log',
        'badge' => 'Space Pioneer',
        'personalization_questions' => [
            [
                'key' => 'space_destination',
                'type' => 'text',
                'question' => 'Where in space would you like to explore?',
                'placeholder' => 'Mars, Moon, Jupiter...',
            ],
            [
                'key' => 'space_mission',
                'type' => 'text',
                'question' => 'What would be your mission in space?',
                'placeholder' => 'Research, colonization, discovery...',
            ],
            [
                'key' => 'astronaut_role',
                'type' => 'mcq',
                'question' => 'What role would you have on a space mission?',
                'options' => [
                    'Commander',
                    'Scientist',
                    'Engineer',
                    'Explorer',
                ],
            ],
            [
                'key' => 'space_discovery',
                'type' => 'chips',
                'question' => 'What would you most want to discover in space?',
                'options' => ['Alien Life', 'New Planets', 'Resources', 'Mysteries', 'Home for Humans'],
            ],
        ],
    ],
    // Continue with remaining templates...
    [
        'id' => 'heart-kindness',
        'icon' => '❤️',
        'title' => 'Heart & Kindness',
        'description' => 'Kindness and emotional intelligence',
        'skills' => ['Empathy', 'Kindness', 'Emotional Intelligence'],
        'activity' => 'Practice empathy and compassion',
        'creates' => 'A 10-page kindness journey',
        'badge' => 'Heart Hero',
        'personalization_questions' => [
            [
                'key' => 'kindness_meaning',
                'type' => 'text',
                'question' => 'What does kindness mean to you?',
                'placeholder' => 'Share your thoughts...',],
            [
                'key' => 'helping_action',
                'type' => 'text',
                'question' => 'How do you like to help others?',
                'placeholder' => 'Listening, sharing, supporting...',
            ],
            [
                'key' => 'empathy_moment',
                'type' => 'mcq',
                'question' => 'When someone is sad, what do you do?',
                'options' => [
                    'Listen to them',
                    'Give them a hug',
                    'Make them smile',
                    'Help solve their problem',
                ],
            ],
            [
                'key' => 'kindness_superpower',
                'type' => 'chips',
                'question' => 'What kindness superpower would you choose?',
                'options' => ['Healing Words', 'Happiness Spreader', 'Problem Solver', 'Comfort Giver', 'Joy Creator'],
            ],
        ],
    ],
    [
        'id' => 'digital-world',
        'icon' => '💻',
        'title' => 'Digital World',
        'description' => 'Digital literacy and technology',
        'skills' => ['Technology', 'Digital Safety', 'Innovation'],
        'activity' => 'Navigate the digital landscape safely',
        'creates' => 'A 10-page tech adventure',
        'badge' => 'Digital Champion',
        'personalization_questions' => [
            [
                'key' => 'tech_interest',
                'type' => 'text',
                'question' => 'What technology fascinates you most?',
                'placeholder' => 'AI, robots, apps, games...',
            ],
            [
                'key' => 'digital_creation',
                'type' => 'text',
                'question' => 'If you could create any digital tool, what would it be?',
                'placeholder' => 'Describe your idea...',
            ],
            [
                'key' => 'tech_role',
                'type' => 'mcq',
                'question' => 'In the digital world, what role suits you?',
                'options' => [
                    'Creator - building new things',
                    'Explorer - discovering possibilities',
                    'Protector - ensuring safety',
                    'Connector - bringing people together',
                ],
            ],
            [
                'key' => 'digital_skill',
                'type' => 'chips',
                'question' => 'What digital skill do you want to master?',
                'options' => ['Coding', 'Design', 'Gaming', 'Video Creation', 'Digital Art'],
            ],
        ],
    ],
    [
        'id' => 'creative-spark',
        'icon' => '🎨',
        'title' => 'Creative Spark',
        'description' => 'Artistic expression and creativity',
        'skills' => ['Art', 'Storytelling', 'Self-Expression'],
        'activity' => 'Create art and tell your story',
        'creates' => 'A 10-page creative portfolio',
        'badge' => 'Creative Genius',
        'personalization_questions' => [
            [
                'key' => 'art_form',
                'type' => 'text',
                'question' => 'What form of art do you love most?',
                'placeholder' => 'Painting, music, writing, dance...',
            ],
            [
                'key' => 'creative_inspiration',
                'type' => 'text',
                'question' => 'What inspires your creativity?',
                'placeholder' => 'Nature, emotions, stories...',
            ],
            [
                'key' => 'artist_type',
                'type' => 'mcq',
                'question' => 'What kind of artist are you?',
                'options' => [
                    'Visual artist',
                    'Performer',
                    'Writer',
                    'Designer',
                ],
            ],
            [
                'key' => 'creative_power',
                'type' => 'chips',
                'question' => 'What creative power would enhance your art?',
                'options' => ['Perfect Colors', 'Instant Inspiration', 'Living Art', 'Emotion Transfer', 'Time Freeze'],
            ],
        ],
    ],
    [
        'id' => 'everyday-heroes',
        'icon' => '🦸',
        'title' => 'Everyday Heroes',
        'description' => 'Heroism and making a positive impact',
        'skills' => ['Leadership', 'Courage', 'Impact'],
        'activity' => 'Discover your inner hero',
        'creates' => 'A 10-page hero journey',
        'badge' => 'Everyday Hero',
        'personalization_questions' => [
            [
                'key' => 'hero_definition',
                'type' => 'text',
                'question' => 'What makes someone a hero?',
                'placeholder' => 'Bravery, kindness, helping...',
            ],
            [
                'key' => 'heroic_act',
                'type' => 'text',
                'question' => 'What heroic act would you like to do?',
                'placeholder' => 'Help someone, stand up for others...',
            ],
            [
                'key' => 'hero_strength',
                'type' => 'mcq',
                'question' => 'What is your greatest hero strength?',
                'options' => [
                    'Courage to stand up',
                    'Kindness to help',
                    'Wisdom to guide',
                    'Strength to protect',
                ],
            ],
            [
                'key' => 'hero_power',
                'type' => 'chips',
                'question' => 'What hero power would you choose?',
                'options' => ['Super Strength', 'Healing Touch', 'Bravery Boost', 'Wisdom Vision', 'Protective Shield'],
            ],
        ],
    ],
    [
        'id' => 'science-lab',
        'icon' => '🔬',
        'title' => 'Science Lab',
        'description' => 'Scientific discovery and experimentation',
        'skills' => ['Science', 'Experiments', 'Discovery'],
        'activity' => 'Conduct experiments and discover science',
        'creates' => 'A 10-page science journal',
        'badge' => 'Young Scientist',
        'personalization_questions' => [
            [
                'key' => 'science_field',
                'type' => 'text',
                'question' => 'What field of science interests you most?',
                'placeholder' => 'Biology, chemistry, physics...',
            ],
            [
                'key' => 'discovery_goal',
                'type' => 'text',
                'question' => 'What would you like to discover or prove?',
                'placeholder' => 'A cure, new species, theory...',
            ],
            [
                'key' => 'scientist_approach',
                'type' => 'mcq',
                'question' => 'How do you approach scientific questions?',
                'options' => [
                    'Experiment and test',
                    'Research and study',
                    'Observe and document',
                    'Question and analyze',
                ],
            ],
            [
                'key' => 'science_tool',
                'type' => 'chips',
                'question' => 'What scientific tool excites you most?',
                'options' => ['Microscope', 'Telescope', 'Lab Equipment', 'Computer Simulations', 'Field Research Gear'],
            ],
        ],
    ],
    [
        'id' => 'time-travelers',
        'icon' => '⏰',
        'title' => 'Time Travelers',
        'description' => 'Historical exploration and learning from the past',
        'skills' => ['History', 'Time Travel', 'Learning'],
        'activity' => 'Travel through time and explore history',
        'creates' => 'A 10-page time travel diary',
        'badge' => 'Time Explorer',
        'personalization_questions' => [
            [
                'key' => 'time_period',
                'type' => 'text',
                'question' => 'What time period would you visit?',
                'placeholder' => 'Ancient Egypt, Renaissance, Future...',
            ],
            [
                'key' => 'historical_curiosity',
                'type' => 'text',
                'question' => 'What historical mystery would you solve?',
                'placeholder' => 'Pyramids, dinosaurs, inventions...',
            ],
            [
                'key' => 'time_traveler_mission',
                'type' => 'mcq',
                'question' => 'What would be your time travel mission?',
                'options' => [
                    'Learn from the past',
                    'Witness great moments',
                    'Meet historical figures',
                    'See how things were built',
                ],
            ],
            [
                'key' => 'time_power',
                'type' => 'chips',
                'question' => 'What time-travel ability would you want?',
                'options' => ['Instant Translation', 'Invisibility', 'Time Freeze', 'Historical Knowledge', 'Safe Return'],
            ],
        ],
    ],
    [
        'id' => 'legacy-builders',
        'icon' => '🏛️',
        'title' => 'Legacy Builders',
        'description' => 'Building lasting impact and leaving a mark',
        'skills' => ['Legacy', 'Impact', 'Vision'],
        'activity' => 'Plan your lasting contribution',
        'creates' => 'A 10-page legacy blueprint',
        'badge' => 'Legacy Maker',
        'personalization_questions' => [
            [
                'key' => 'legacy_vision',
                'type' => 'text',
                'question' => 'What positive change do you want to leave in the world?',
                'placeholder' => 'A better community, innovation, inspiration...',
            ],
            [
                'key' => 'remembered_for',
                'type' => 'text',
                'question' => 'What do you want to be remembered for?',
                'placeholder' => 'Kindness, creativity, leadership...',
            ],
            [
                'key' => 'legacy_approach',
                'type' => 'mcq',
                'question' => 'How will you build your legacy?',
                'options' => [
                    'Through helping others',
                    'Through creating something new',
                    'Through inspiring people',
                    'Through solving big problems',
                ],
            ],
            [
                'key' => 'impact_focus',
                'type' => 'chips',
                'question' => 'Where do you want to make the biggest impact?',
                'options' => ['Community', 'Education', 'Environment', 'Technology', 'Arts & Culture'],
            ],
        ],
    ],
];